#Set service name
spring.application.name=auth-service

#Set eureka-client instance id
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

#If port is 0 spring boot assigns port dynamically,
#0 because I am going to create multiple auth-service instances
server.port=0


#Data source configs
#H2 settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb  
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa  
spring.datasource.password=
