#Set application name
spring.application.name=auth-service
#Set eureka-client instance id
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
#If port is 0 spring boot assigns port dynamically,
# 0 because I am going to create multiple auth-service instances
server.port=0
#Set eureka registry-service server url
eureka.client.service-url.default-zone=http://localhost:8761/eureka

