#Set application name
spring.application.name=image-service
#Set eureka-client instance id
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
#port 0 because of multiple auth-service instances
server.port=0
#Set eureka registry-service server url
eureka.client.service-url.default-zone=http://localhost:8761/eureka